name: Change message

on:
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    # runs-on: ubuntu-latest

    runs-on: self-hosted
    steps:
    
      - uses: actions/checkout@v3

      - name: Code Review
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
           chmod +x gradlew
           ./gradlew build   
           cp build/libs/testing-web-0.0.1-SNAPSHOT.jar .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 0lb4p/feature-ms-pablo-morales-mensaje:latest

  deploy:

    runs-on: self-hosted
    needs: build
    steps:

    - uses: actions/checkout@v3
    
    - name: Deploy in k8s
      run: |
        kubectl apply -f deployment.yml
